### ISSUE TITLE
IEEEmadC

### ISSUE THREAD

**Issue by SangramChavan** [Juboraj-Sarker/MedicineAlert#1]
Could not find the executable file can you include in the repo ?

**Comment by Juboraj-Sarker** [comment]
Okay I will include it within couple of hours.
Thanks

**Comment by Juboraj-Sarker** [comment]
Hello,
I have uploaded the executable file in the "runnable_file" directory and
also updated in git. Please check it out.
I have included the url here.
Thank you

URL:
https://github.com/Juboraj-Sarker/MedicineAlert/tree/master/runnable_file
